ALTER TABLE "ChatRoom" ADD COLUMN IF NOT EXISTS "userLastReadMessageId" INTEGER;
ALTER TABLE "ChatRoom" ADD COLUMN IF NOT EXISTS "adminLastReadMessageId" INTEGER;
ALTER TABLE "ChatRoom" ADD COLUMN IF NOT EXISTS "guestLastReadMessageId" INTEGER;
